# Generated by Django 5.2.4 on 2025-07-12 11:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('ENT', 'Entrada'), ('PRIN', 'Prato Principal'), ('BEB', 'Bebida'), ('SOB', 'Sobremesa'), ('OUT', 'Outros')], default='PRIN', max_length=4, verbose_name='Tipo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ingredientes', models.TextField(blank=True, verbose_name='Ingredientes')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ementa/itens/', verbose_name='Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ementa', to='ementa.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item da Ementa',
                'verbose_name_plural': 'Itens da Ementa',
                'ordering': ['tipo', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'disponivel'], name='ementa_emen_tipo_7e886c_idx')],
            },
        ),
    ]
