# Generated by Django 5.2.4 on 2025-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ementa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
